"""The oneview design tokens, read from the vendored spec — never retyped.

X-11 applied to a design system: a colour transcribed by hand is a colour that will differ
from the other two skins by one digit, and the difference stays invisible until three
screenshots are put side by side in a launch deck.

X-6 applied to a design system: **the spec is a hard requirement, never an optional
extra.** A missing or drifted spec **raises**. There is no bundled palette to fall back to,
because a viewer that silently uses last week's palette when it cannot find the spec is a
viewer that will be shipped with last week's palette.

THE PINS ARE COMPUTED HERE, NOT INHERITED
------------------------------------------
onedoor's viewer pins the same two digests, and today they match. They are still recomputed
and re-declared in this repository rather than copied across, because a pin inherited rather
than checked is a pin nobody checked — and the whole point of a pin is that somebody did.

WHAT §4 SAYS, AND WHAT THIS MODULE REFUSES TO LET DRIFT
--------------------------------------------------------
    semantic green/red never double as brand accent; seal gold never signals state.

Core → Canary Response 015 §2 ruled how that sentence survives contact with the reference
mockup, which renders a recorded state in seal: **seal is brand, and brand only; recorded
facts get bold ink; §4 stands as written.** When a spec and its reference mockup disagree,
the resolution that makes the fewest written sentences false wins. onewatch therefore builds
to §4 and inherits nothing from the mockup's violation — including §5.4's
anchor-status-in-seal, which is the same defect inside the spec's own body and is core's to
correct at the spec.
"""
from __future__ import annotations

import hashlib
import re
from functools import lru_cache
from pathlib import Path

SPEC_PATH = Path(__file__).parent / "_vendor" / "ONEVIEW_DESIGN_SPEC.md"
"""Core's spec, vendored INTO the package rather than read from `docs/`.

A repo directory does not travel in a wheel: an installed `canary` would find no spec and
the viewer would be unusable outside a checkout. The delivery lives on the clean disk
channel at `onedoor/docs/oneview/`; this is the byte-identical copy that ships.
"""

SPEC_DIGEST = "72b428004c28c6fdc42257264a4aa7b834d4e12ca22fed9c3d78dbbd5f8e96b0"
"""sha256 of the whole vendored spec file. Generated by tooling, never typed (X-11)."""

SPEC_FENCE_DIGEST = "c066604cf754a4f88407f4a0ba64b8b5b385fd02519e6e4ab930e72cb0744c27"
"""sha256 of the spec's §4 CSS fence contents. Generated by tooling, never typed."""

_FENCE = re.compile(r"```css\n(.*?)```", re.S)
_DECL = re.compile(r"(--[a-z-]+)\s*:\s*(#[0-9A-Fa-f]{6})")

#: Colours the page may use that are not tokens, each with the reason it is not one. An
#: allowance without a reason beside it becomes a habit; this dict is the whole exception
#: list and it is asserted in the tests.
ALLOWED_NON_TOKEN_COLOURS: dict[str, str] = {}


class TokenError(RuntimeError):
    """The spec could not be read, or does not carry what was vendored from it."""


@lru_cache(maxsize=1)
def css_block() -> str:
    """The spec's §4 fence, verbatim, with its digest checked before it is used."""
    if not SPEC_PATH.is_file():
        raise TokenError(
            f"the oneview design spec is not where the viewer expects it: {SPEC_PATH}. "
            f"The design system is a hard requirement (X-6); there is no bundled palette "
            f"to fall back to.")
    match = _FENCE.search(SPEC_PATH.read_text(encoding="utf-8"))
    if match is None:
        raise TokenError("the design spec has no ```css fence; §4 is the token authority")
    block = match.group(1)
    digest = hashlib.sha256(block.encode("utf-8")).hexdigest()
    if digest != SPEC_FENCE_DIGEST:
        raise TokenError(
            f"the spec's token block has changed: it hashes to {digest[:12]}… and this "
            f"build pinned {SPEC_FENCE_DIGEST[:12]}…. Re-vendor deliberately; do not "
            f"absorb a design change without looking at it.")
    return block


@lru_cache(maxsize=1)
def palette() -> dict[str, str]:
    """`{token name: #rrggbb}` parsed from the vendored block."""
    return {name: value.lower() for name, value in _DECL.findall(css_block())}


def hex_values() -> frozenset[str]:
    """Every colour the design system declares, lowercased for comparison."""
    return frozenset(palette().values()) | frozenset(ALLOWED_NON_TOKEN_COLOURS)


def root_css() -> str:
    """The `:root` rule for the emitted page.

    The vendored block carries its two font lines as spec prose rather than CSS
    (`font-sans: 'Archivo' (400/500/600/700), fallback system sans`), so the custom
    properties are declared here and the *stacks* they name are the spec's. Colours come
    through untouched, which is the half that must not be paraphrased.
    """
    declarations = "\n  ".join(
        line.strip() for line in css_block().splitlines()
        if line.strip().startswith("--"))
    return (
        ":root{\n  " + declarations
        + "\n  --mono:'IBM Plex Mono',ui-monospace,SFMono-Regular,Menlo,monospace;"
        + "\n  --sans:'Archivo',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;"
        + "\n}")
